name: Build and Push Docker Image (Dev) - Client

on:
  push:
    branches: ['dev/client']
  pull_request:
    branches: ['dev/client']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract commit SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Convert repository name to lowercase
        id: lowercase_repo
        run: echo "repo_lower=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: client
          file: client/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase_repo.outputs.repo_lower }}/client:latest
            ghcr.io/${{ steps.lowercase_repo.outputs.repo_lower }}/client:dev
            ghcr.io/${{ steps.lowercase_repo.outputs.repo_lower }}/client:${{ steps.sha.outputs.sha_short }}

  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        run: |
          gh pr edit "$PR_URL" --add-label "client"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
