name: Build and Push Docker Images (Dev)

on:
  push:
    branches: ['dev/server']
  pull_request:
    branches: ['dev/server']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target_arch: linux/amd64
            image_tag: latest
            dockerfile: Dockerfile.amd64
            short_arch: amd64
          - target_arch: linux/arm64
            image_tag: macos-latest
            dockerfile: Dockerfile.arm64
            short_arch: arm64
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract commit SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Convert repository name to lowercase
        id: lowercase_repo
        run: echo "repo_lower=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: server
          file: server/${{ matrix.dockerfile }}
          platforms: ${{ matrix.target_arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase_repo.outputs.repo_lower }}/server:${{ matrix.image_tag }}
            ghcr.io/${{ steps.lowercase_repo.outputs.repo_lower }}/server:${{ steps.sha.outputs.sha_short }}-${{ matrix.short_arch }}
