name: Tag and Push Release Image

on:
  push:
    branches: ['main']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine changed project
        id: changed-project
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          if [[ "$CHANGED_FILES" == *"client/"* ]]; then
            echo "project=client" >> $GITHUB_OUTPUT
          elif [[ "$CHANGED_FILES" == *"server/"* ]]; then
            echo "project=server" >> $GITHUB_OUTPUT
          else
            echo "project=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract commit SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Determine next version
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 19.0.3
          branch: main
          plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/docker
          preset: angular
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push client tagged image
        if: ${{ steps.changed-project.outputs.project == 'client' && steps.semantic-release.outputs.new_release_published == 'true' }}
        run: |
          docker tag ghcr.io/${{ github.repository }}/client:${{ steps.sha.outputs.sha_short }} ghcr.io/${{ github.repository }}/client:${{ steps.semantic-release.outputs.new_release_version }}
          docker push ghcr.io/${{ github.repository }}/client:${{ steps.semantic-release.outputs.new_release_version }}
          echo "Pushed client release tag ${{ steps.semantic-release.outputs.new_release_version }}"

      - name: Push server tagged image
        if: ${{ steps.changed-project.outputs.project == 'server' && steps.semantic-release.outputs.new_release_published == 'true' }}
        run: |
          docker tag ghcr.io/${{ github.repository }}/server:${{ steps.sha.outputs.sha_short }} ghcr.io/${{ github.repository }}/server:${{ steps.semantic-release.outputs.new_release_version }}
          docker push ghcr.io/${{ github.repository }}/server:${{ steps.semantic-release.outputs.new_release_version }}
          echo "Pushed server release tag ${{ steps.semantic-release.outputs.new_release_version }}"

  add_release_label:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.result == 'success' && steps.semantic-release.outputs.new_release_published == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add release label
        run: |
          gh pr edit "$GITHUB_REF_NAME" --add-label "RELEASE-${{ steps.semantic-release.outputs.new_release_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
